set up flash messages
kimikonagano/chat-space pull request #8
Opened 2016-12-30 13:32 UTC by kimikonagano

# WHAT
フラッシュメッセージ機能追加
# WHY
通知がくることで、状況理解がすぐできるから

2016-12-30 13:38 UTC, hc0208 requested changes

2016-12-30 13:38 UTC, hc070208 commented on config/application.rb
> -    end
あれ消さないんじゃ...笑

2016-12-30 13:38 UTC, hc070208 commented on app/views/layouts/application.html.haml
> +      %p.alert.alert-error= alert
ほぼ同じ記述だから1つにまとめられそうだな。

2016-12-30 13:44 UTC, kimikonagano commented on app/views/layouts/application.html.haml
> +      %p.alert.alert-error= alert
了解しますた！

2016-12-30 13:44 UTC, kimikonagano commented on config/application.rb
> -    end
あれーーーーーーー！

2016-12-30 22:43 UTC, hc0208 requested changes

2016-12-30 22:43 UTC, hc070208 commented on app/views/layouts/application.html.haml
> +      %div{class: "alert alert-#{key}"}= value
お！すばらしい！
できると思わなかった笑

2016-12-30 22:43 UTC, hc070208 commented on app/views/layouts/application.html.haml
> +    /   %p.alert.alert-error= alert
コメントアウトは消そう！

2016-12-30 22:43 UTC, hc070208 commented on app/views/layouts/application.html.haml
> +      %div{class: "alert alert-#{key}"}= value
{のあとと}の前は半角スペース1つ入れよう

2016-12-31 01:15 UTC, kimikonagano commented on app/views/layouts/application.html.haml
> +    /   %p.alert.alert-error= alert
はい！

2016-12-31 01:18 UTC, kimikonagano commented on app/views/layouts/application.html.haml
> +      %div{class: "alert alert-#{key}"}= value
＼＼\\٩( 'ω' )و //／／

2016-12-31 01:51 UTC, kimikonagano commented on app/views/layouts/application.html.haml
> +      %div{class: "alert alert-#{key}"}= value
恐縮です(°ω°)

2016-12-31 01:58 UTC, hc070208 commented on app/views/layouts/application.html.haml
> +      %div{class: "alert alert-#{key}"}= value
まじか笑
%div{ class: "alert alert-#{key}" }= value
でいけなかった？

2016-12-31 02:02 UTC, kimikonagano commented on app/views/layouts/application.html.haml
> +      %div{class: "alert alert-#{key}"}= value
すいません、日本語読むの苦手で笑
上記でいけました！

2016-12-31 02:05 UTC, hc070208 commented
LGTM

2016-12-31 02:07 UTC, merged