created group function
kimikonagano/chat-space pull request #9
Opened 2017-01-13 16:44 UTC by kimikonagano

# WHAT
グループ作成機能、メンバー追加機能の作成

# WHY
グループチャットを可能にするため

2017-01-13 18:07 UTC, b-i-hide commented on app/assets/javascripts/groups.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
このファイルいらないかな

2017-01-13 18:07 UTC, b-i-hide commented on app/assets/stylesheets/_group.scss
> +  .chat-group-form__errors {
せっかくだから&記法使いたいね

2017-01-13 18:07 UTC, b-i-hide commented on app/assets/stylesheets/_group.scss
> +    .chat-group-form__field--left {
この辺も

2017-01-13 18:07 UTC, b-i-hide commented on app/controllers/groups_controller.rb
> +    Group.create(group_params)
成功した時と失敗した時で場合分けしよう！

2017-01-13 18:07 UTC, b-i-hide commented on app/controllers/groups_controller.rb
> +  def update
こっちも

2017-01-13 18:07 UTC, b-i-hide commented on db/migrate/20170112193822_create_chat_group_users.rb
> +      t.integer :user_id, foreign_key: :true
reference型で書こう！

2017-01-13 18:07 UTC, b-i-hide commented on db/migrate/20170112193822_create_chat_group_users.rb
> +      t.integer :group_id, foreign_key: :true
こっちも

2017-01-13 18:07 UTC, b-i-hide commented on app/views/groups/edit.html.haml
> +  %form#edit_chat_group_22.edit_chat_group{"accept-charset" => "UTF-8", :action => "/chat_groups/22", :method => "post"}
こっちもform_forで書こうね〜！

2017-01-17 00:29 UTC, hc0208 requested changes

2017-01-17 00:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +    @group = Group.create(group_params)
Group.newだね

2017-01-17 00:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +      render :index, id: @group
redirect_toの方がいいかな。あとflashメッセージもほしい

2017-01-17 00:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +    if @group.save
@group.saveじゃなくて、@group.update(group_params)だね

2017-01-17 00:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +      render :index, id: @group
これもredirect toで

2017-01-17 00:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +    @group = Group.find(params[:id])
@group = Group.find(params[:id])
って同じ記述がいくつかあるからbefore_actionでまとめよう

2017-01-17 00:29 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +    params.require(:group).permit(:name, { user_ids: [] })
{}はいらないね

2017-01-17 00:29 UTC, hc070208 commented on app/views/groups/edit.html.haml
> +    /     #user-search-result
いらないコメントアウトは消しておこう！

2017-01-17 00:29 UTC, hc070208 commented on app/views/messages/index.html.haml
> +        = link_to 'Edit', edit_group_path(@group.id), class: "chat-header__edit-btn"
edit_group_path(@group)だけでいけるよ

2017-01-17 00:29 UTC, hc070208 commented on config/routes.rb
> +  get 'groups' => 'groups#index'
下のresourcesの中に書こう

2017-01-17 03:53 UTC, kimikonagano commented on app/views/groups/edit.html.haml
> +    /     #user-search-result
のちのちインクリメンタルサーチで使うから残しておいて大丈夫って言わたのですが、やっぱり消した方がいいでしょうか！

2017-01-17 04:14 UTC, kimikonagano commented on app/controllers/groups_controller.rb
> +      render :index, id: @group
承知しました！

2017-01-30 23:36 UTC, hc0208 requested changes

2017-01-30 23:36 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +      redirect_to action: :new
flashメッセージ欲しいね

2017-01-30 23:36 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +    if @group.update(group_params)
@group.update(group_params)が2つある

2017-01-30 23:36 UTC, hc070208 commented on app/views/messages/index.html.haml
> +        = link_to 'Edit', edit_group_path(@group.id), class: "chat-header__edit-btn"
これもね

2017-01-30 23:36 UTC, hc070208 commented on config/routes.rb
> +  resources :groups, only: [:new, :create, :show, :edit, :update]
exceptの方が短いかな

2017-01-31 14:29 UTC, kimikonagano commented on app/views/messages/index.html.haml
> +        = link_to 'Edit', edit_group_path(@group.id), class: "chat-header__edit-btn"
同じこと指摘されないように注意します！

2017-01-31 14:30 UTC, kimikonagano commented on app/controllers/groups_controller.rb
> +    if @group.update(group_params)
注意深くなります。ご指摘ありがとうございます！

2017-01-31 14:31 UTC, kimikonagano commented on config/routes.rb
> +  resources :groups, only: [:new, :create, :show, :edit, :update]
神様

2017-01-31 14:36 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +      redirect_to action: :new
これは。。。

2017-01-31 14:36 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +      redirect_to action: :edit
失敗のflashメッセージも！

2017-01-31 14:38 UTC, kimikonagano commented on app/controllers/groups_controller.rb
> +      redirect_to action: :new
直します、、！

2017-01-31 14:55 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +        グループ名を入力してください"
なるほどねー。これ出したかったら他の書き方するしかないんだけど、無理そうなら「グループ名を入力してください」だけでいいよ 🙆

2017-02-03 05:37 UTC, kimikonagano commented
↓ 実装したviewになります！ ↓
https://gyazo.com/bbde6c0a9214b396e9c440d836a6af5d

2017-02-03 05:47 UTC, hc070208 commented
LGTM

2017-02-03 05:51 UTC, merged